
source("3_cluster/src/seasonal_metric_cluster.R")
source("3_cluster/src/gage_year_coverage_by_cluster.R")

p3_targets_list<- list(
  
  ##Cluster analysis to make model regions from FDC metrics
  tar_target(p3_metric_names,
             {colnames(p2_FDC_metrics)[-c(1,grep(colnames(p2_FDC_metrics), pattern = 'mhfdc'))]
             },
             deployment = 'main'
  ),
  tar_target(p3_metric_names_quants,
             {as.character(NE_quants)},
             deployment = 'main'
  ),
  tar_target(p3_metric_names_quants_agg,
             {c(str_c(as.character(NE_quants)[1:5], collapse = ','), 
                str_c(as.character(NE_quants)[6:10], collapse = ','))
             },
             deployment = 'main'
  ),
  tar_target(p3_metric_names_quants_all_agg,
             str_c(as.character(NE_quants)[1:10], collapse = ','),
             deployment = 'main'
  ),
  #Low flow regions
  tar_target(p3_metric_names_low,
             {colnames(p2_FDC_metrics_low)[
               -c(1,
                  grep(colnames(p2_FDC_metrics_low), pattern = 'mhfdc'),
                  #Removing columns with NAs
                  grep(colnames(p2_FDC_metrics_low), pattern = 'q0.005'),
                  grep(colnames(p2_FDC_metrics_low), pattern = 'q0.01')
               )
             ]
             },
             deployment = 'main'
  ),
  tar_target(p3_metric_names_quants_low,
             {as.character(NE_quants_low[-c(1,2)])},
             deployment = 'main'
  ),
  tar_target(p3_metric_names_quants_agg_low,
             {c(str_c(as.character(NE_quants_low)[4:7], collapse = ','), 
                str_c(as.character(NE_quants_low)[8:13], collapse = ','))
             },
             deployment = 'main'
  ),
  
  #barplot for all metrics, averaged over all gages
  tar_target(p3_seasonal_barplot_COUNS_png,
             plot_seasonal_barplot(metric_mat = p2_FDC_metrics_season,
                                   metric = p3_metric_names,
                                   season_months = season_months,
                                   by_cluster = FALSE,
                                   dir_out = '3_cluster/out/seasonal_plots/barplots/CONUS/'),
             map(p3_metric_names),
             deployment = 'worker',
             format = 'file'
  ),
  #Low flow
  tar_target(p3_seasonal_barplot_COUNS_low_png,
             plot_seasonal_barplot(metric_mat = p2_FDC_metrics_season_low,
                                   metric = p3_metric_names_low,
                                   season_months = season_months,
                                   by_cluster = FALSE,
                                   dir_out = '3_cluster/out/seasonal_plots_LowFlow/barplots/CONUS/'),
             map(p3_metric_names_low),
             deployment = 'worker',
             format = 'file'
  ),
  
  #Compute clusters
  tar_target(p3_FDC_clusters,
             seasonal_metric_cluster(metric_mat = p2_FDC_metrics_season,
                                     metric = p3_metric_names,
                                     dist_method = 'euclidean'),
             map(p3_metric_names),
             deployment = 'worker'
  ),
  tar_target(p3_FDC_clusters_quants,
             seasonal_metric_cluster(metric_mat = p2_FDC_metrics_season,
                                     metric = p3_metric_names_quants,
                                     dist_method = 'euclidean'),
             map(p3_metric_names_quants),
             deployment = 'worker'
  ),
  tar_target(p3_FDC_clusters_quants_agg,
             seasonal_metric_cluster(metric_mat = p2_FDC_metrics_season,
                                     metric = p3_metric_names_quants_agg,
                                     dist_method = 'euclidean',
                                     quantile_agg = TRUE),
             map(p3_metric_names_quants_agg),
             deployment = 'worker'
  ),
  tar_target(p3_FDC_clusters_quants_all_agg,
             seasonal_metric_cluster(metric_mat = p2_FDC_metrics_season,
                                     metric = p3_metric_names_quants_all_agg,
                                     dist_method = 'euclidean',
                                     quantile_agg = TRUE),
             map(p3_metric_names_quants_all_agg),
             deployment = 'worker'
  ),
  #Low flow
  tar_target(p3_FDC_clusters_low,
             seasonal_metric_cluster(metric_mat = p2_FDC_metrics_season_low,
                                     metric = p3_metric_names_low,
                                     dist_method = 'euclidean'),
             map(p3_metric_names_low),
             deployment = 'worker'
  ),
  tar_target(p3_FDC_clusters_quants_low,
             seasonal_metric_cluster(metric_mat = p2_FDC_metrics_season_low,
                                     metric = p3_metric_names_quants_low,
                                     dist_method = 'euclidean'),
             map(p3_metric_names_quants_low),
             deployment = 'worker'
  ),
  tar_target(p3_FDC_clusters_quants_low_novhfdc3,
             seasonal_metric_cluster(metric_mat = p2_FDC_metrics_season_low %>% 
                                       select(-contains('vhfdc3')),
                                     metric = p3_metric_names_quants_low,
                                     dist_method = 'euclidean'),
             map(p3_metric_names_quants_low),
             deployment = 'worker'
  ),
  tar_target(p3_FDC_clusters_quants_low_freq,
             seasonal_metric_cluster(metric_mat = p2_FDC_metrics_season_low %>% 
                                       select(site_num, contains('fhfdc')),
                                     metric = p3_metric_names_quants_low,
                                     dist_method = 'euclidean'),
             map(p3_metric_names_quants_low),
             deployment = 'worker'
  ),
  tar_target(p3_FDC_clusters_quants_agg_low,
             seasonal_metric_cluster(metric_mat = p2_FDC_metrics_season_low,
                                     metric = p3_metric_names_quants_agg_low,
                                     dist_method = 'euclidean',
                                     quantile_agg = TRUE),
             map(p3_metric_names_quants_agg_low),
             deployment = 'worker'
  ),
  tar_target(p3_FDC_clusters_quants_agg_low_novhfdc3,
             seasonal_metric_cluster(metric_mat = p2_FDC_metrics_season_low %>% 
                                       select(-contains('vhfdc3')),
                                     metric = p3_metric_names_quants_agg_low,
                                     dist_method = 'euclidean',
                                     quantile_agg = TRUE),
             map(p3_metric_names_quants_agg_low),
             deployment = 'worker'
  ),
  tar_target(p3_FDC_clusters_quants_agg_low_freq,
             seasonal_metric_cluster(metric_mat = p2_FDC_metrics_season_low %>% 
                                       select(site_num, contains('fhfdc')),
                                     metric = p3_metric_names_quants_agg_low,
                                     dist_method = 'euclidean',
                                     quantile_agg = TRUE),
             map(p3_metric_names_quants_agg_low),
             deployment = 'worker'
  ),
  
  #Select only the best clustering method
  tar_target(p3_FDC_best_cluster_method,
             select_cluster_method(clusts = p3_FDC_clusters),
             deployment = 'main'
  ),
  tar_target(p3_FDC_best_cluster_method_quants,
             select_cluster_method(clusts = p3_FDC_clusters_quants),
             deployment = 'main'
  ),
  tar_target(p3_FDC_best_cluster_method_quants_agg,
             select_cluster_method(clusts = p3_FDC_clusters_quants_agg, 
                                   quantile_agg = TRUE),
             deployment = 'main'
  ),
  tar_target(p3_FDC_best_cluster_method_quants_all_agg,
             select_cluster_method(clusts = p3_FDC_clusters_quants_all_agg, 
                                   quantile_agg = TRUE),
             deployment = 'main'
  ),
  #Low flow
  tar_target(p3_FDC_best_cluster_method_low,
             select_cluster_method(clusts = p3_FDC_clusters_low),
             deployment = 'main'
  ),
  tar_target(p3_FDC_best_cluster_method_quants_low,
             select_cluster_method(clusts = p3_FDC_clusters_quants_low),
             deployment = 'main'
  ),
  tar_target(p3_FDC_best_cluster_method_quants_low_novhfdc3,
             select_cluster_method(clusts = p3_FDC_clusters_quants_low_novhfdc3),
             deployment = 'main'
  ),
  tar_target(p3_FDC_best_cluster_method_quants_low_freq,
             select_cluster_method(clusts = p3_FDC_clusters_quants_low_freq),
             deployment = 'main'
  ),
  tar_target(p3_FDC_best_cluster_method_quants_agg_low,
             select_cluster_method(clusts = p3_FDC_clusters_quants_agg_low, 
                                   quantile_agg = TRUE),
             deployment = 'main'
  ),
  tar_target(p3_FDC_best_cluster_method_quants_agg_low_novhfdc3,
             select_cluster_method(clusts = p3_FDC_clusters_quants_agg_low_novhfdc3, 
                                   quantile_agg = TRUE),
             deployment = 'main'
  ),
  tar_target(p3_FDC_best_cluster_method_quants_agg_low_freq,
             select_cluster_method(clusts = p3_FDC_clusters_quants_agg_low_freq, 
                                   quantile_agg = TRUE),
             deployment = 'main'
  ),
  
  #Compute cluster diagnostics
  tar_target(p3_FDC_cluster_diagnostics,
             compute_cluster_diagnostics(clusts = p3_FDC_clusters,
                                         metric_mat = p2_FDC_metrics_season,
                                         kmin = 2, kmax = 20,
                                         alpha = 0.05, boot = 50,
                                         index = 'all', 
                                         dist_method = 'euclidean',
                                         clust_method = 'ward.D2'),
             map(p3_FDC_clusters),
             deployment = 'worker'
  ),
  tar_target(p3_FDC_cluster_diagnostics_quants,
             compute_cluster_diagnostics(clusts = p3_FDC_clusters_quants,
                                         metric_mat = p2_FDC_metrics_season,
                                         kmin = 2, kmax = 20,
                                         alpha = 0.05, boot = 50,
                                         index = 'all', 
                                         dist_method = 'euclidean',
                                         clust_method = 'ward.D2'),
             map(p3_FDC_clusters_quants),
             deployment = 'worker'
  ),
  tar_target(p3_FDC_cluster_diagnostics_quants_agg,
             compute_cluster_diagnostics(clusts = p3_FDC_clusters_quants_agg,
                                         metric_mat = p2_FDC_metrics_season,
                                         kmin = 2, kmax = 20,
                                         alpha = 0.05, boot = 50,
                                         index = 'all', 
                                         dist_method = 'euclidean',
                                         clust_method = 'ward.D2',
                                         quantile_agg = TRUE),
             map(p3_FDC_clusters_quants_agg),
             deployment = 'worker'
  ),
  tar_target(p3_FDC_cluster_diagnostics_quants_all_agg,
             compute_cluster_diagnostics(clusts = p3_FDC_clusters_quants_all_agg,
                                         metric_mat = p2_FDC_metrics_season,
                                         kmin = 2, kmax = 20,
                                         alpha = 0.05, boot = 50,
                                         index = 'all', 
                                         dist_method = 'euclidean',
                                         clust_method = 'ward.D2',
                                         quantile_agg = TRUE),
             map(p3_FDC_clusters_quants_all_agg),
             deployment = 'worker'
  ),
  #Low flow
  tar_target(p3_FDC_cluster_diagnostics_low,
             compute_cluster_diagnostics(clusts = p3_FDC_clusters_low,
                                         metric_mat = p2_FDC_metrics_season_low,
                                         kmin = 2, kmax = 20,
                                         alpha = 0.05, boot = 50,
                                         index = 'all', 
                                         dist_method = 'euclidean',
                                         clust_method = 'ward.D2'),
             map(p3_FDC_clusters_low),
             deployment = 'worker'
  ),
  tar_target(p3_FDC_cluster_diagnostics_quants_low,
             compute_cluster_diagnostics(clusts = p3_FDC_clusters_quants_low,
                                         metric_mat = p2_FDC_metrics_season_low,
                                         kmin = 2, kmax = 20,
                                         alpha = 0.05, boot = 50,
                                         index = 'all', 
                                         dist_method = 'euclidean',
                                         clust_method = 'ward.D2'),
             map(p3_FDC_clusters_quants_low),
             deployment = 'worker'
  ),
  tar_target(p3_FDC_cluster_diagnostics_quants_low_novhfdc3,
             compute_cluster_diagnostics(clusts = p3_FDC_clusters_quants_low_novhfdc3,
                                         metric_mat = p2_FDC_metrics_season_low %>%
                                           select(-contains('vhfdc3')),
                                         kmin = 2, kmax = 20,
                                         alpha = 0.05, boot = 50,
                                         index = 'all', 
                                         dist_method = 'euclidean',
                                         clust_method = 'ward.D2'),
             map(p3_FDC_clusters_quants_low_novhfdc3),
             deployment = 'worker'
  ),
  tar_target(p3_FDC_cluster_diagnostics_quants_low_freq,
             compute_cluster_diagnostics(clusts = p3_FDC_clusters_quants_low_freq,
                                         metric_mat = p2_FDC_metrics_season_low %>%
                                           select(site_num, contains('fhfdc')),
                                         kmin = 2, kmax = 20,
                                         alpha = 0.05, boot = 50,
                                         index = 'all', 
                                         dist_method = 'euclidean',
                                         clust_method = 'ward.D2'),
             map(p3_FDC_clusters_quants_low_freq),
             deployment = 'worker'
  ),
  tar_target(p3_FDC_cluster_diagnostics_quants_agg_low,
             compute_cluster_diagnostics(clusts = p3_FDC_clusters_quants_agg_low,
                                         metric_mat = p2_FDC_metrics_season_low,
                                         kmin = 2, kmax = 20,
                                         alpha = 0.05, boot = 50,
                                         index = 'all', 
                                         dist_method = 'euclidean',
                                         clust_method = 'ward.D2',
                                         quantile_agg = TRUE),
             map(p3_FDC_clusters_quants_agg_low),
             deployment = 'worker'
  ),
  tar_target(p3_FDC_cluster_diagnostics_quants_agg_low_novhfdc3,
             compute_cluster_diagnostics(clusts = p3_FDC_clusters_quants_agg_low_novhfdc3,
                                         metric_mat = p2_FDC_metrics_season_low %>%
                                           select(-contains('vhfdc3')),
                                         kmin = 2, kmax = 20,
                                         alpha = 0.05, boot = 50,
                                         index = 'all', 
                                         dist_method = 'euclidean',
                                         clust_method = 'ward.D2',
                                         quantile_agg = TRUE),
             map(p3_FDC_clusters_quants_agg_low_novhfdc3),
             deployment = 'worker'
  ),
  tar_target(p3_FDC_cluster_diagnostics_quants_agg_low_freq,
             compute_cluster_diagnostics(clusts = p3_FDC_clusters_quants_agg_low_freq,
                                         metric_mat = p2_FDC_metrics_season_low %>%
                                           select(site_num, contains('fhfdc')),
                                         kmin = 2, kmax = 20,
                                         alpha = 0.05, boot = 50,
                                         index = 'all', 
                                         dist_method = 'euclidean',
                                         clust_method = 'ward.D2',
                                         quantile_agg = TRUE),
             map(p3_FDC_clusters_quants_agg_low_freq),
             deployment = 'worker'
  ),
  
  #Plot diagnostics for clusters
  tar_target(p3_FDC_cluster_diagnostics_png,
             plot_cluster_diagnostics(clusts = p3_FDC_clusters,
                                      metric_mat = p2_FDC_metrics_season,
                                      nbclust_metrics = p3_FDC_cluster_diagnostics,
                                      dist_method = 'euclidean',
                                      clust_method = 'ward.D2',
                                      dir_out = '3_cluster/out/seasonal_plots/diagnostics/'),
             map(p3_FDC_clusters, p3_FDC_cluster_diagnostics),
             deployment = 'worker',
             format = 'file'
  ),
  tar_target(p3_FDC_cluster_diagnostics_quants_png,
             plot_cluster_diagnostics(clusts = p3_FDC_clusters_quants,
                                      metric_mat = p2_FDC_metrics_season,
                                      nbclust_metrics = p3_FDC_cluster_diagnostics_quants,
                                      dist_method = 'euclidean',
                                      clust_method = 'ward.D2',
                                      dir_out = '3_cluster/out/seasonal_plots/diagnostics/by_quantiles'),
             map(p3_FDC_clusters_quants, p3_FDC_cluster_diagnostics_quants),
             deployment = 'worker',
             format = 'file'
  ),
  tar_target(p3_FDC_cluster_diagnostics_quants_agg_png,
             plot_cluster_diagnostics(clusts = p3_FDC_clusters_quants_agg,
                                      metric_mat = p2_FDC_metrics_season,
                                      nbclust_metrics = p3_FDC_cluster_diagnostics_quants_agg,
                                      dist_method = 'euclidean',
                                      clust_method = 'ward.D2',
                                      dir_out = '3_cluster/out/seasonal_plots/diagnostics/by_agg_quantiles',
                                      quantile_agg = TRUE),
             map(p3_FDC_clusters_quants_agg, p3_FDC_cluster_diagnostics_quants_agg),
             deployment = 'worker',
             format = 'file'
  ),
  tar_target(p3_FDC_cluster_diagnostics_quants_all_agg_png,
             plot_cluster_diagnostics(clusts = p3_FDC_clusters_quants_all_agg,
                                      metric_mat = p2_FDC_metrics_season,
                                      nbclust_metrics = p3_FDC_cluster_diagnostics_quants_all_agg,
                                      dist_method = 'euclidean',
                                      clust_method = 'ward.D2',
                                      dir_out = '3_cluster/out/seasonal_plots/diagnostics/by_all_agg_quantiles',
                                      quantile_agg = TRUE),
             map(p3_FDC_clusters_quants_all_agg, p3_FDC_cluster_diagnostics_quants_all_agg),
             deployment = 'worker',
             format = 'file'
  ),
  #Low flow
  tar_target(p3_FDC_cluster_diagnostics_low_png,
             plot_cluster_diagnostics(clusts = p3_FDC_clusters_low,
                                      metric_mat = p2_FDC_metrics_season_low,
                                      nbclust_metrics = p3_FDC_cluster_diagnostics_low,
                                      dist_method = 'euclidean',
                                      clust_method = 'ward.D2',
                                      dir_out = '3_cluster/out/seasonal_plots_LowFlow/diagnostics/'),
             map(p3_FDC_clusters_low, p3_FDC_cluster_diagnostics_low),
             deployment = 'worker',
             format = 'file'
  ),
  tar_target(p3_FDC_cluster_diagnostics_quants_low_png,
             plot_cluster_diagnostics(clusts = p3_FDC_clusters_quants_low,
                                      metric_mat = p2_FDC_metrics_season_low,
                                      nbclust_metrics = p3_FDC_cluster_diagnostics_quants_low,
                                      dist_method = 'euclidean',
                                      clust_method = 'ward.D2',
                                      dir_out = '3_cluster/out/seasonal_plots_LowFlow/diagnostics/by_quantiles'),
             map(p3_FDC_clusters_quants_low, p3_FDC_cluster_diagnostics_quants_low),
             deployment = 'worker',
             format = 'file'
  ),
  tar_target(p3_FDC_cluster_diagnostics_quants_low_novhfdc3_png,
             plot_cluster_diagnostics(clusts = p3_FDC_clusters_quants_low_novhfdc3,
                                      metric_mat = p2_FDC_metrics_season_low %>%
                                        select(-contains('vhfdc3')),
                                      nbclust_metrics = p3_FDC_cluster_diagnostics_quants_low_novhfdc3,
                                      dist_method = 'euclidean',
                                      clust_method = 'ward.D2',
                                      dir_out = '3_cluster/out/seasonal_plots_LowFlow_noHighVolume/diagnostics/by_quantiles'),
             map(p3_FDC_clusters_quants_low_novhfdc3, p3_FDC_cluster_diagnostics_quants_low_novhfdc3),
             deployment = 'worker',
             format = 'file'
  ),
  tar_target(p3_FDC_cluster_diagnostics_quants_low_freq_png,
             plot_cluster_diagnostics(clusts = p3_FDC_clusters_quants_low_freq,
                                      metric_mat = p2_FDC_metrics_season_low %>%
                                        select(site_num, contains('fhfdc')),
                                      nbclust_metrics = p3_FDC_cluster_diagnostics_quants_low_freq,
                                      dist_method = 'euclidean',
                                      clust_method = 'ward.D2',
                                      dir_out = '3_cluster/out/seasonal_plots_LowFlow_freq/diagnostics/by_quantiles'),
             map(p3_FDC_clusters_quants_low_freq, p3_FDC_cluster_diagnostics_quants_low_freq),
             deployment = 'worker',
             format = 'file'
  ),
  tar_target(p3_FDC_cluster_diagnostics_quants_agg_low_png,
             plot_cluster_diagnostics(clusts = p3_FDC_clusters_quants_agg_low,
                                      metric_mat = p2_FDC_metrics_season_low,
                                      nbclust_metrics = p3_FDC_cluster_diagnostics_quants_agg_low,
                                      dist_method = 'euclidean',
                                      clust_method = 'ward.D2',
                                      dir_out = '3_cluster/out/seasonal_plots_LowFlow/diagnostics/by_agg_quantiles',
                                      quantile_agg = TRUE),
             map(p3_FDC_clusters_quants_agg_low, p3_FDC_cluster_diagnostics_quants_agg_low),
             deployment = 'worker',
             format = 'file'
  ),
  tar_target(p3_FDC_cluster_diagnostics_quants_agg_low_novhfdc3_png,
             plot_cluster_diagnostics(clusts = p3_FDC_clusters_quants_agg_low_novhfdc3,
                                      metric_mat = p2_FDC_metrics_season_low %>%
                                        select(-contains('vhfdc3')),
                                      nbclust_metrics = p3_FDC_cluster_diagnostics_quants_agg_low_novhfdc3,
                                      dist_method = 'euclidean',
                                      clust_method = 'ward.D2',
                                      dir_out = '3_cluster/out/seasonal_plots_LowFlow_noHighVolume/diagnostics/by_agg_quantiles',
                                      quantile_agg = TRUE),
             map(p3_FDC_clusters_quants_agg_low_novhfdc3, p3_FDC_cluster_diagnostics_quants_agg_low_novhfdc3),
             deployment = 'worker',
             format = 'file'
  ),
  tar_target(p3_FDC_cluster_diagnostics_quants_agg_low_freq_png,
             plot_cluster_diagnostics(clusts = p3_FDC_clusters_quants_agg_low_freq,
                                      metric_mat = p2_FDC_metrics_season_low %>%
                                        select(site_num, contains('fhfdc')),
                                      nbclust_metrics = p3_FDC_cluster_diagnostics_quants_agg_low_freq,
                                      dist_method = 'euclidean',
                                      clust_method = 'ward.D2',
                                      dir_out = '3_cluster/out/seasonal_plots_LowFlow_freq/diagnostics/by_agg_quantiles',
                                      quantile_agg = TRUE),
             map(p3_FDC_clusters_quants_agg_low_freq, p3_FDC_cluster_diagnostics_quants_agg_low_freq),
             deployment = 'worker',
             format = 'file'
  ),
  
  #Assign cluster numbers to gages
  tar_target(p3_gages_clusters,
             add_cluster_to_gages(clusts = p3_FDC_clusters,
                                  screened_sites = p1_screened_site_list_season,
                                  best_clust = p3_FDC_best_cluster_method,
                                  min_clusts = 3, max_clusts = 15, by_clusts = 4),
             deployment = 'main'
  ),
  tar_target(p3_gages_clusters_quants,
             add_cluster_to_gages(clusts = p3_FDC_clusters_quants,
                                  screened_sites = p1_screened_site_list_season,
                                  best_clust = p3_FDC_best_cluster_method_quants,
                                  min_clusts = 3, max_clusts = 15, by_clusts = 4),
             deployment = 'main'
  ),
  tar_target(p3_gages_clusters_quants_agg,
             add_cluster_to_gages(clusts = p3_FDC_clusters_quants_agg,
                                  screened_sites = p1_screened_site_list_season,
                                  best_clust = p3_FDC_best_cluster_method_quants_agg,
                                  min_clusts = 3, max_clusts = 15, by_clusts = 4,
                                  quantile_agg = TRUE),
             deployment = 'main'
  ),
  tar_target(p3_gages_clusters_quants_agg_selected,
             add_cluster_to_gages(clusts = p3_FDC_clusters_quants_agg,
                                  screened_sites = p1_screened_site_list_season,
                                  best_clust = p3_FDC_best_cluster_method_quants_agg,
                                  min_clusts = 4, max_clusts = 6, by_clusts = 1,
                                  quantile_agg = TRUE),
             deployment = 'main'
  ),
  tar_target(p3_gages_clusters_quants_all_agg,
             add_cluster_to_gages(clusts = p3_FDC_clusters_quants_all_agg,
                                  screened_sites = p1_screened_site_list_season,
                                  best_clust = p3_FDC_best_cluster_method_quants_all_agg,
                                  min_clusts = 3, max_clusts = 15, by_clusts = 2,
                                  quantile_agg = TRUE),
             deployment = 'main'
  ),
  #Low flow
  tar_target(p3_gages_clusters_low,
             add_cluster_to_gages(clusts = p3_FDC_clusters_low,
                                  screened_sites = p1_screened_site_list_season,
                                  best_clust = p3_FDC_best_cluster_method_low,
                                  min_clusts = 3, max_clusts = 15, by_clusts = 2),
             deployment = 'main'
  ),
  tar_target(p3_gages_clusters_quants_low,
             add_cluster_to_gages(clusts = p3_FDC_clusters_quants_low,
                                  screened_sites = p1_screened_site_list_season,
                                  best_clust = p3_FDC_best_cluster_method_quants_low,
                                  min_clusts = 3, max_clusts = 15, by_clusts = 2),
             deployment = 'main'
  ),
  tar_target(p3_gages_clusters_quants_low_novhfdc3,
             add_cluster_to_gages(clusts = p3_FDC_clusters_quants_low_novhfdc3,
                                  screened_sites = p1_screened_site_list_season,
                                  best_clust = p3_FDC_best_cluster_method_quants_low_novhfdc3,
                                  min_clusts = 3, max_clusts = 15, by_clusts = 2),
             deployment = 'main'
  ),
  tar_target(p3_gages_clusters_quants_low_freq,
             add_cluster_to_gages(clusts = p3_FDC_clusters_quants_low_freq,
                                  screened_sites = p1_screened_site_list_season,
                                  best_clust = p3_FDC_best_cluster_method_quants_low_freq,
                                  min_clusts = 3, max_clusts = 15, by_clusts = 2),
             deployment = 'main'
  ),
  tar_target(p3_gages_clusters_quants_agg_low,
             add_cluster_to_gages(clusts = p3_FDC_clusters_quants_agg_low,
                                  screened_sites = p1_screened_site_list_season,
                                  best_clust = p3_FDC_best_cluster_method_quants_agg_low,
                                  min_clusts = 3, max_clusts = 15, by_clusts = 2,
                                  quantile_agg = TRUE),
             deployment = 'main'
  ),
  tar_target(p3_gages_clusters_quants_agg_low_novhfdc3,
             add_cluster_to_gages(clusts = p3_FDC_clusters_quants_agg_low_novhfdc3,
                                  screened_sites = p1_screened_site_list_season,
                                  best_clust = p3_FDC_best_cluster_method_quants_agg_low_novhfdc3,
                                  min_clusts = 3, max_clusts = 15, by_clusts = 2,
                                  quantile_agg = TRUE),
             deployment = 'main'
  ),
  tar_target(p3_gages_clusters_quants_agg_low_freq,
             add_cluster_to_gages(clusts = p3_FDC_clusters_quants_agg_low_freq,
                                  screened_sites = p1_screened_site_list_season,
                                  best_clust = p3_FDC_best_cluster_method_quants_agg_low_freq,
                                  min_clusts = 3, max_clusts = 15, by_clusts = 2,
                                  quantile_agg = TRUE),
             deployment = 'main'
  ),
  
  #Assign cluster column names to a target for later branch iteration
  tar_target(p3_cluster_cols,
             colnames(p3_gages_clusters)[-1],
             deployment = 'main'
  ),
  tar_target(p3_cluster_cols_quants,
             colnames(p3_gages_clusters_quants)[-1],
             deployment = 'main'
  ),
  tar_target(p3_cluster_cols_quants_agg,
             colnames(p3_gages_clusters_quants_agg)[-1],
             deployment = 'main'
  ),
  tar_target(p3_cluster_cols_quants_agg_selected,
             colnames(p3_gages_clusters_quants_agg_selected)[-1],
             deployment = 'main'
  ),
  tar_target(p3_cluster_cols_quants_all_agg,
             colnames(p3_gages_clusters_quants_all_agg)[-1],
             deployment = 'main'
  ),
  #Low flow
  tar_target(p3_cluster_cols_low,
             colnames(p3_gages_clusters_low)[-1],
             deployment = 'main'
  ),
  tar_target(p3_cluster_cols_quants_low,
             colnames(p3_gages_clusters_quants_low)[-1],
             deployment = 'main'
  ),
  tar_target(p3_cluster_cols_quants_low_novhfdc3,
             colnames(p3_gages_clusters_quants_low_novhfdc3)[-1],
             deployment = 'main'
  ),
  tar_target(p3_cluster_cols_quants_low_freq,
             colnames(p3_gages_clusters_quants_low_freq)[-1],
             deployment = 'main'
  ),
  tar_target(p3_cluster_cols_quants_agg_low,
             colnames(p3_gages_clusters_quants_agg_low)[-1],
             deployment = 'main'
  ),
  tar_target(p3_cluster_cols_quants_agg_low_novhfdc3,
             colnames(p3_gages_clusters_quants_agg_low_novhfdc3)[-1],
             deployment = 'main'
  ),
  tar_target(p3_cluster_cols_quants_agg_low_freq,
             colnames(p3_gages_clusters_quants_agg_low_freq)[-1],
             deployment = 'main'
  ),
  
  #Plot maps of gages with clusters
  tar_target(p3_cluster_map_png,
             plot_cluster_map(gages = p1_feature_vars_g2_sf,
                              cluster_table = p3_gages_clusters,
                              dir_out = '3_cluster/out/seasonal_plots/maps/'),
             deployment = 'main',
             format = 'file'
  ),
  tar_target(p3_cluster_map_quants_png,
             plot_cluster_map(gages = p1_feature_vars_g2_sf,
                              cluster_table = p3_gages_clusters_quants,
                              dir_out = '3_cluster/out/seasonal_plots/maps/by_quantiles'),
             deployment = 'main',
             format = 'file'
  ),
  tar_target(p3_cluster_map_quants_agg_png,
             plot_cluster_map(gages = p1_feature_vars_g2_sf,
                              cluster_table = p3_gages_clusters_quants_agg,
                              dir_out = '3_cluster/out/seasonal_plots/maps/by_agg_quantiles',
                              facet=FALSE),
             deployment = 'main',
             format = 'file'
  ),
  tar_target(p3_cluster_map_quants_agg_facet_png,
             plot_cluster_map(gages = p1_feature_vars_g2_sf,
                              cluster_table = p3_gages_clusters_quants_agg,
                              dir_out = '3_cluster/out/seasonal_plots/maps/by_agg_quantiles',
                              facet = TRUE),
             deployment = 'main',
             format = 'file'
  ),
  tar_target(p3_cluster_map_quants_agg_selected_png,
             plot_cluster_map(gages = p1_feature_vars_g2_sf,
                              cluster_table = p3_gages_clusters_quants_agg_selected,
                              dir_out = '3_cluster/out/seasonal_plots/maps/by_agg_quantiles',
                              facet=FALSE),
             deployment = 'main',
             format = 'file'
  ),
  tar_target(p3_cluster_map_quants_agg_facet_selected_png,
             plot_cluster_map(gages = p1_feature_vars_g2_sf,
                              cluster_table = p3_gages_clusters_quants_agg_selected,
                              dir_out = '3_cluster/out/seasonal_plots/maps/by_agg_quantiles',
                              facet = TRUE),
             deployment = 'main',
             format = 'file'
  ),
  tar_target(p3_cluster_map_quants_all_agg_png,
             plot_cluster_map(gages = p1_feature_vars_g2_sf,
                              cluster_table = p3_gages_clusters_quants_all_agg,
                              dir_out = '3_cluster/out/seasonal_plots/maps/by_all_agg_quantiles',
                              facet=FALSE),
             deployment = 'main',
             format = 'file'
  ),
  tar_target(p3_cluster_map_quants_all_agg_facet_png,
             plot_cluster_map(gages = p1_feature_vars_g2_sf,
                              cluster_table = p3_gages_clusters_quants_all_agg,
                              dir_out = '3_cluster/out/seasonal_plots/maps/by_all_agg_quantiles',
                              facet = TRUE),
             deployment = 'main',
             format = 'file'
  ),
  #Low flow
  tar_target(p3_cluster_map_low_png,
             plot_cluster_map(gages = p1_feature_vars_g2_sf,
                              cluster_table = p3_gages_clusters_low,
                              dir_out = '3_cluster/out/seasonal_plots_LowFlow/maps/'),
             deployment = 'main',
             format = 'file'
  ),
  tar_target(p3_cluster_map_quants_low_png,
             plot_cluster_map(gages = p1_feature_vars_g2_sf,
                              cluster_table = p3_gages_clusters_quants_low,
                              dir_out = '3_cluster/out/seasonal_plots_LowFlow/maps/by_quantiles'),
             deployment = 'main',
             format = 'file'
  ),
  tar_target(p3_cluster_map_quants_low_facet_png,
             plot_cluster_map(gages = p1_feature_vars_g2_sf,
                              cluster_table = p3_gages_clusters_quants_low,
                              dir_out = '3_cluster/out/seasonal_plots_LowFlow/maps/by_quantiles',
                              facet = TRUE),
             deployment = 'main',
             format = 'file'
  ),
  tar_target(p3_cluster_map_quants_low_novhfdc3_png,
             plot_cluster_map(gages = p1_feature_vars_g2_sf,
                              cluster_table = p3_gages_clusters_quants_low_novhfdc3,
                              dir_out = '3_cluster/out/seasonal_plots_LowFlow_noHighVolume/maps/by_quantiles'),
             deployment = 'main',
             format = 'file'
  ),
  tar_target(p3_cluster_map_quants_low_novhfdc3_facet_png,
             plot_cluster_map(gages = p1_feature_vars_g2_sf,
                              cluster_table = p3_gages_clusters_quants_low_novhfdc3,
                              dir_out = '3_cluster/out/seasonal_plots_LowFlow_noHighVolume/maps/by_quantiles',
                              facet = TRUE),
             deployment = 'main',
             format = 'file'
  ),
  tar_target(p3_cluster_map_quants_low_freq_png,
             plot_cluster_map(gages = p1_feature_vars_g2_sf,
                              cluster_table = p3_gages_clusters_quants_low_freq,
                              dir_out = '3_cluster/out/seasonal_plots_LowFlow_freq/maps/by_quantiles'),
             deployment = 'main',
             format = 'file'
  ),
  tar_target(p3_cluster_map_quants_low_freq_facet_png,
             plot_cluster_map(gages = p1_feature_vars_g2_sf,
                              cluster_table = p3_gages_clusters_quants_low_freq,
                              dir_out = '3_cluster/out/seasonal_plots_LowFlow_freq/maps/by_quantiles',
                              facet = TRUE),
             deployment = 'main',
             format = 'file'
  ),
  tar_target(p3_cluster_map_quants_agg_low_png,
             plot_cluster_map(gages = p1_feature_vars_g2_sf,
                              cluster_table = p3_gages_clusters_quants_agg_low,
                              dir_out = '3_cluster/out/seasonal_plots_LowFlow/maps/by_agg_quantiles',
                              facet=FALSE),
             deployment = 'main',
             format = 'file'
  ),
  tar_target(p3_cluster_map_quants_agg_low_facet_png,
             plot_cluster_map(gages = p1_feature_vars_g2_sf,
                              cluster_table = p3_gages_clusters_quants_agg_low,
                              dir_out = '3_cluster/out/seasonal_plots_LowFlow/maps/by_agg_quantiles',
                              facet = TRUE),
             deployment = 'main',
             format = 'file'
  ),
  tar_target(p3_cluster_map_quants_agg_low_novhfdc3_png,
             plot_cluster_map(gages = p1_feature_vars_g2_sf,
                              cluster_table = p3_gages_clusters_quants_agg_low_novhfdc3,
                              dir_out = '3_cluster/out/seasonal_plots_LowFlow_noHighVolume/maps/by_agg_quantiles',
                              facet=FALSE),
             deployment = 'main',
             format = 'file'
  ),
  tar_target(p3_cluster_map_quants_agg_low_novhfdc3_facet_png,
             plot_cluster_map(gages = p1_feature_vars_g2_sf,
                              cluster_table = p3_gages_clusters_quants_agg_low_novhfdc3,
                              dir_out = '3_cluster/out/seasonal_plots_LowFlow_noHighVolume/maps/by_agg_quantiles',
                              facet = TRUE),
             deployment = 'main',
             format = 'file'
  ),
  tar_target(p3_cluster_map_quants_agg_low_freq_png,
             plot_cluster_map(gages = p1_feature_vars_g2_sf,
                              cluster_table = p3_gages_clusters_quants_agg_low_freq,
                              dir_out = '3_cluster/out/seasonal_plots_LowFlow_freq/maps/by_agg_quantiles',
                              facet=FALSE),
             deployment = 'main',
             format = 'file'
  ),
  tar_target(p3_cluster_map_quants_agg_low_freq_facet_png,
             plot_cluster_map(gages = p1_feature_vars_g2_sf,
                              cluster_table = p3_gages_clusters_quants_agg_low_freq,
                              dir_out = '3_cluster/out/seasonal_plots_LowFlow_freq/maps/by_agg_quantiles',
                              facet = TRUE),
             deployment = 'main',
             format = 'file'
  ),
  
  #barplot for all metrics, averaged over cluster gages
  tar_target(p3_seasonal_barplot_clusters_png,
             plot_seasonal_barplot(metric_mat = p2_FDC_metrics_season,
                                   metric = p3_metric_names,
                                   season_months = season_months,
                                   by_cluster = TRUE,
                                   panel_plot = TRUE,
                                   cluster_table = p3_gages_clusters,
                                   dir_out = '3_cluster/out/seasonal_plots/barplots/'),
             map(p3_metric_names),
             deployment = 'worker',
             format = 'file'
  ),
  tar_target(p3_seasonal_barplot_clusters_quants_png,
             plot_seasonal_barplot(metric_mat = p2_FDC_metrics_season,
                                   metric = p3_metric_names_quants,
                                   season_months = season_months,
                                   by_cluster = TRUE,
                                   panel_plot = TRUE,
                                   cluster_table = p3_gages_clusters_quants,
                                   dir_out = '3_cluster/out/seasonal_plots/barplots/by_quantiles',
                                   by_quantile = TRUE),
             map(p3_metric_names_quants),
             deployment = 'worker',
             format = 'file'
  ),
  tar_target(p3_seasonal_barplot_clusters_quants_agg_png,
             plot_seasonal_barplot(metric_mat = p2_FDC_metrics_season,
                                   metric = p3_metric_names_quants_agg,
                                   season_months = season_months,
                                   by_cluster = TRUE,
                                   panel_plot = TRUE,
                                   cluster_table = p3_gages_clusters_quants_agg,
                                   dir_out = '3_cluster/out/seasonal_plots/barplots/by_agg_quantiles',
                                   quantile_agg = TRUE,
                                   by_quantile = TRUE),
             map(p3_metric_names_quants_agg),
             deployment = 'worker',
             format = 'file'
  ),
  tar_target(p3_seasonal_barplot_clusters_quants_agg_selected_png,
             plot_seasonal_barplot(metric_mat = p2_FDC_metrics_season,
                                   metric = p3_metric_names_quants_agg,
                                   season_months = season_months,
                                   by_cluster = TRUE,
                                   panel_plot = TRUE,
                                   cluster_table = p3_gages_clusters_quants_agg_selected,
                                   dir_out = '3_cluster/out/seasonal_plots/barplots/by_agg_quantiles',
                                   quantile_agg = TRUE,
                                   by_quantile = TRUE),
             map(p3_metric_names_quants_agg),
             deployment = 'worker',
             format = 'file'
  ),
  tar_target(p3_seasonal_barplot_clusters_quants_all_agg_png,
             plot_seasonal_barplot(metric_mat = p2_FDC_metrics_season,
                                   metric = p3_metric_names_quants_all_agg,
                                   season_months = season_months,
                                   by_cluster = TRUE,
                                   panel_plot = TRUE,
                                   cluster_table = p3_gages_clusters_quants_all_agg,
                                   dir_out = '3_cluster/out/seasonal_plots/barplots/by_all_agg_quantiles',
                                   quantile_agg = TRUE,
                                   by_quantile = TRUE),
             map(p3_metric_names_quants_all_agg),
             deployment = 'worker',
             format = 'file'
  ),
  #Low flow
  tar_target(p3_seasonal_barplot_clusters_low_png,
             plot_seasonal_barplot(metric_mat = p2_FDC_metrics_season_low,
                                   metric = p3_metric_names_low,
                                   season_months = season_months,
                                   by_cluster = TRUE,
                                   panel_plot = TRUE,
                                   cluster_table = p3_gages_clusters_low,
                                   dir_out = '3_cluster/out/seasonal_plots_LowFlow/barplots/'),
             map(p3_metric_names_low),
             deployment = 'worker',
             format = 'file'
  ),
  tar_target(p3_seasonal_barplot_clusters_quants_low_png,
             plot_seasonal_barplot(metric_mat = p2_FDC_metrics_season_low,
                                   metric = p3_metric_names_quants_low,
                                   season_months = season_months,
                                   by_cluster = TRUE,
                                   panel_plot = TRUE,
                                   cluster_table = p3_gages_clusters_quants_low,
                                   dir_out = '3_cluster/out/seasonal_plots_LowFlow/barplots/by_quantiles',
                                   by_quantile = TRUE),
             map(p3_metric_names_quants_low),
             deployment = 'worker',
             format = 'file'
  ),
  tar_target(p3_seasonal_barplot_clusters_quants_low_novhfdc3_png,
             plot_seasonal_barplot(metric_mat = p2_FDC_metrics_season_low %>%
                                     select(-contains('vhfdc3')),
                                   metric = p3_metric_names_quants_low,
                                   season_months = season_months,
                                   by_cluster = TRUE,
                                   panel_plot = TRUE,
                                   cluster_table = p3_gages_clusters_quants_low_novhfdc3,
                                   dir_out = '3_cluster/out/seasonal_plots_LowFlow_noHighVolume/barplots/by_quantiles',
                                   by_quantile = TRUE),
             map(p3_metric_names_quants_low),
             deployment = 'worker',
             format = 'file'
  ),
  tar_target(p3_seasonal_barplot_clusters_quants_low_freq_png,
             plot_seasonal_barplot(metric_mat = p2_FDC_metrics_season_low %>%
                                     select(site_num, contains('fhfdc')),
                                   metric = p3_metric_names_quants_low,
                                   season_months = season_months,
                                   by_cluster = TRUE,
                                   panel_plot = TRUE,
                                   cluster_table = p3_gages_clusters_quants_low_freq,
                                   dir_out = '3_cluster/out/seasonal_plots_LowFlow_freq/barplots/by_quantiles',
                                   by_quantile = TRUE),
             map(p3_metric_names_quants_low),
             deployment = 'worker',
             format = 'file'
  ),
  tar_target(p3_seasonal_barplot_clusters_quants_agg_low_png,
             plot_seasonal_barplot(metric_mat = p2_FDC_metrics_season_low,
                                   metric = p3_metric_names_quants_agg_low,
                                   season_months = season_months,
                                   by_cluster = TRUE,
                                   panel_plot = TRUE,
                                   cluster_table = p3_gages_clusters_quants_agg_low,
                                   dir_out = '3_cluster/out/seasonal_plots_LowFlow/barplots/by_agg_quantiles',
                                   quantile_agg = TRUE,
                                   by_quantile = TRUE),
             map(p3_metric_names_quants_agg_low),
             deployment = 'worker',
             format = 'file'
  ),
  tar_target(p3_seasonal_barplot_clusters_quants_agg_low_novhfdc3_png,
             plot_seasonal_barplot(metric_mat = p2_FDC_metrics_season_low %>%
                                     select(-contains('vhfdc3')),
                                   metric = p3_metric_names_quants_agg_low,
                                   season_months = season_months,
                                   by_cluster = TRUE,
                                   panel_plot = TRUE,
                                   cluster_table = p3_gages_clusters_quants_agg_low_novhfdc3,
                                   dir_out = '3_cluster/out/seasonal_plots_LowFlow_noHighVolume/barplots/by_agg_quantiles',
                                   quantile_agg = TRUE,
                                   by_quantile = TRUE),
             map(p3_metric_names_quants_agg_low),
             deployment = 'worker',
             format = 'file'
  ),
  tar_target(p3_seasonal_barplot_clusters_quants_agg_low_freq_png,
             plot_seasonal_barplot(metric_mat = p2_FDC_metrics_season_low %>%
                                     select(site_num, contains('fhfdc')),
                                   metric = p3_metric_names_quants_agg_low,
                                   season_months = season_months,
                                   by_cluster = TRUE,
                                   panel_plot = TRUE,
                                   cluster_table = p3_gages_clusters_quants_agg_low_freq,
                                   dir_out = '3_cluster/out/seasonal_plots_LowFlow_freq/barplots/by_agg_quantiles',
                                   quantile_agg = TRUE,
                                   by_quantile = TRUE),
             map(p3_metric_names_quants_agg_low),
             deployment = 'worker',
             format = 'file'
  ),
  tar_target(p3_period_of_record_plots,
             plot_data_coverage(clean_daily_flow = p1_clean_daily_flow, 
                                 cluster_table <- p3_gages_clusters_quants_agg_selected %>%
                                   select(ID, contains('_k5')) %>%
                                   rename(midhigh = '0.5,0.55,0.6,0.65,0.7_k5',
                                          high = '0.75,0.8,0.85,0.9,0.95_k5'), 
                                 dir_out = '3_cluster/out'))
  
)